const express = require("express")
const app = express()
const medicineLogic = require("./services/medicineLogic")
const mongodb = require("./databaseConnection/connect")

app.listen(5500,()=>console.log("listening to port 5500"))
app.use(express.json())
app.post("/addNewMedicine",medicineLogic.createNewMedicine)
app.post("/deleteMedicine",medicineLogic.deleteMedicine)
app.get("/getMedicine",medicineLogic.getMedicine)
